# version: "3.3"

# services:
#   db:
#     image: mysql:5.7
#     volumes:
#       - db_data:/var/lib/mysql
#     restart: always
#     environment:
#       MYSQL_ROOT_PASSWORD: wordpress
#       MYSQL_DATABASE: wordpress
#       MYSQL_USER: wordpress
#       MYSQL_PASSWORD: wordpress
#     ports:
#       - "3310:3306"

#   wordpress:
#     depends_on:
#       - db
#     image: wordpress:latest
#     volumes:
#       - wordpress_data:/var/www/html
#     ports:
#       - "8050:80"
#     restart: always
#     environment:
#       WORDPRESS_DB_HOST: db:3306
#       WORDPRESS_DB_USER: wordpress
#       WORDPRESS_DB_PASSWORD: wordpress
#       WORDPRESS_DB_NAME: wordpress

#   phpmyadmin:
#     depends_on:
#       - db
#     image: phpmyadmin/phpmyadmin
#     restart: always
#     ports:
#       - "8080:80" # Expose phpMyAdmin on port 8080 of the host
#     environment:
#       PMA_HOST: db
#       PMA_USER: wordpress # Use the WordPress database user
#       PMA_PASSWORD: wordpress # Use the WordPress database password

# volumes:
#   db_data: {}
#   wordpress_data: {}

version: "3.3"

services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    ports:
      - "3310:3306"

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    volumes:
      - wordpress_data:/var/www/html
      - /home/usmang/practice/wp/fictional-uni:/var/www/html/wp-content/themes/new-fictional-uni # Mount your theme directory
    ports:
      - "8050:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DEBUG: "true"

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8080:80" # Expose phpMyAdmin on port 8080 of the host
    environment:
      PMA_HOST: db
      PMA_USER: wordpress # Use the WordPress database user
      PMA_PASSWORD: wordpress # Use the WordPress database password

volumes:
  db_data: {}
  wordpress_data: {}
